### PR TITLE
updates for Drupal v9 deployment

### PR DESCRIPTION
**Pull request by gamerf**
*Issue #, if available:*
https://github.com/aws-quickstart/quickstart-drupal/issues/25

*Description of changes:*
Amended the CloudFormation templates to add support for Drupal 9 and updated the PHP runtimes to latest supported (defaulting to php 7.4)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by vsnyc** [comment]
Thank you @gamerf - appreciate the contribution. I'll review this on Monday.

**Comment by dgomesbr** [comment]
Hello @vsnyc, any update? Got another customer wanting @gamerf's patch.

**Comment by vsnyc** [comment]
Changes are merged, unfortunately it didn't track properly as the target on this PR was the main branch and not develop. See commit https://github.com/aws-quickstart/quickstart-drupal/commit/a4abf17b93451ca2edbaf4d7b938f58e47398954 for details.

I had to do a few cleanups:
1. remove .taskcat directory - see commit https://github.com/aws-quickstart/quickstart-drupal/commit/7b05ff58f83b71a3cd97e1686d5ce3f4dae873ca
2. change test settings to use regional buckets -  see commit https://github.com/aws-quickstart/quickstart-drupal/commit/cce09266d3306b100abd3748ffff079c406c78a9

**Comment by gamerf** [comment]
Hello @vsync, thanks for merging back to the aws-quickstart:develop branch.

How do we now publish the changes to the main branch and make it available to the customers?

The link to the templates https://fwd.aws/B3R4x in the https://aws.amazon.com/quickstart/architecture/drupal/ page still points to the old version, and the documentation in those pages and the pdf on https://fwd.aws/yWE7G needs updating

**Comment by vsnyc** [comment]
@gamerf - that part is automated. I looked at our CI and realized that the develop branch submodule needed an update. The changes are tested, merged to main and pushed to S3. The launch links should now point to the new version.

**Pull request closed without merging**
